<?php

const MIN_LEN_ARGS_MAKE_TASK = 2;
const MAX_LEN_ARGS_MAKE_TASK = 4;
const MIN_LEN_ARGS_CLOSE_TASK = 1;
const MAX_LEN_ARGS_CLOSE_TASK = 4;
const MAX_MESSAGE_LEN = 3000;
const MAX_COST_FOR_TASK = 30;